apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::022745511146:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022745511146:role/eksctl-eksctl-demo-nodegroup-ng-8-NodeInstanceRole-MJ4GLN86VDL7
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-27T12:46:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1607"
  uid: 9af6fecf-7ea5-4d62-b86e-215407a28526
